### ISSUE TITLE
admin login credentials

### ISSUE THREAD

**Issue by seanjsm** [tahmid-ni7/Content-Management#1]
cant login as the admin

**Comment by tahmid-ni7** [comment]
I am updating the SQL file. You can download it and put your server again. Then admin login will work. I forgot the previous admin password that's why I update it.

**for admin login:**
Email: admin@system.com
Password: admin&123

> Thanks. If you feel it beneficial follow and star

**Comment by tahmid-ni7** [comment]
- [ ] @seanjs)

>

**Comment by seanjsm** [comment]
> I am updating the SQL file. You can download it and put your server again. Then admin login will work. I forgot the previous admin password that's why I update it.
> 
> **for admin login:**
> Email: [admin@system.com](mailto:admin@system.com)
> Password: admin&123
> 
> > Thanks. If you feel it beneficial follow and star

**Comment by seanjsm** [comment]
thanks @tahmid-ni7 ... already gave a star, btw is there a way I could add a filter where students on the same dept as the teacher can only see the file, and also I'm new to this
